### ISSUE TITLE
mod_jem: Hour:Minutes format is broken

### ISSUE THREAD

**Issue by jobrusche** [Heklaterriol/JEM-Project#106]
Fresh installed Joomla 4.2.8, no other components than JEM beta4 2.39 /  PHP 8.0.32

JEM default basic settings shows  Format Time   H:M  -> Front-end calendar module shows  2digit hour : 3character abbreviated month

Changing setting of Format Time into H:i -> save -> Front-end calendar module shows  2digit hour : 2digit minutes
This should be de the default setting for Format Time at installation time.

**Comment by mckillo** [comment]
Commit with the solution.
I suppose that you know, but you can change the setting JEM installed in:

![JEM for JL4 - Change Format DAte into JEM setting](https://user-images.githubusercontent.com/2765316/222290106-63360d2e-4c5c-4b09-b97c-ed4488ddf984.jpg)

I have up a commit with the solution to fix this issue in the code, default setting too (see fece3a025a83783e656b4723e3826e7ac74694c8)

**Comment by jobrusche** [comment]
I know, but my point is that the default at installation time is faulty. The installation should contain a correct default setting.

**Comment by jobrusche** [comment]
I suppose this wil appear in beta4 2.40 ?

**Comment by mckillo** [comment]
I hope so :-), for the moment, there is manual solution in the JEM setting. it's easy to solve it.

**Comment by jojo12** [comment]
solution: in mod_jem.xml
replace formatdate
default=""
and
replace formattime
default=""
then mod_jem uses global JEM settings

**Comment by mckillo** [comment]
Commit was the solution for event view (when link event in the module is clicked). 
@jojo12: I think that is better to write the right formar, I mean, 'H:i' into mod_jem.xml that leave the fields empty, because the format are different, as you can see in the image.

![JEM for JL4 - time format broken line if time format module is empty](https://user-images.githubusercontent.com/2765316/222419178-9551a9b3-fe34-4831-a11e-139c967f7ce3.jpg)

I think it is better to change `default="%H:%M"` with `default="H:i"` into mod_jem.xml. So, it don't need to change helpers.php (don't add timename).

I have added other commit with proposal solution (see commit b0a6dd4841752b3d685dc75fc14670f82d741e0b) )

**Comment by jojo12** [comment]
I don't agree. In german we normally use timesuffix "Uhr". I need the timesuffix. Because of this is the change in the helper.php.
And it depends on the width of the position. 
For the timeformat and dateformat it is better to let default the global setting. When you want to change, then set local here!

**Comment by jojo12** [comment]
ok, I agree: you don't have to change the helper.php!

**Comment by mckillo** [comment]
In global setting, can be set 'tiem Suffix' (Uhr, h, ...), I suppose that these params have a default setting in english. I test JEM with Joomla in english in a first time, after I change a spanish to configure.
I think, that it's better to have active the format setting in the module by experince, because the formats are different in each setting (between event page and event module views). For example: long style (page) vs short style (module) for date & times & composition of other characters (,./-).
