### ISSUE TITLE
cosmetic? why I can't decide no more, how big my images should be (or in simplelist or in eventdetails?

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#116]
That's not cosmetic! That's robbering!

**Comment by mckillo** [comment]
I don't understand, I have missed something :-)

**Comment by jojo12** [comment]
I installed the changes "small fixes before JEM4.
And now in JEMsettings the possibility to choose image width is away!
Then in responsive style simplelist and eventdetails, the images are very small (much too small). I tried to change, but it is not possible. For me and I think many others, this is worse than before.
Why this possibility is away?

**Comment by Heklaterriol** [comment]
Oh, if it was me, then it is a mistake – it was not my intention to remove image width. I check it.

**Comment by Heklaterriol** [comment]
Please give me more details, where exactly you encountered it.

**Comment by Heklaterriol** [comment]
JEM 2.3.5:
![JEM235](https://user-images.githubusercontent.com/28540581/224090431-96c58717-8fa5-41fa-8e26-142c23d0ccc6.png)
JEM 4:
![JEM4](https://user-images.githubusercontent.com/28540581/224090400-3a4fa81d-23a9-4d18-bb3b-075b4b997243.png)
JEM 4 with cosmetics:
![JEM4 opt](https://user-images.githubusercontent.com/28540581/224090417-6b13aa7d-0be4-4b3c-9847-8f402a8df26f.png)

Looks similar …

**Comment by mckillo** [comment]
I have cheked it and for me, It works.
JEM for JL4 +  2.3.9 with small fix - image400x300 show small 200x150 in right side (Single Event) when JEM setting is 200x200

![JEM for JL4 - 2 3 9 with small fix - image400x300 show small 200x150 when setting is 200x200](https://user-images.githubusercontent.com/2765316/224092631-85d6a386-d4fe-4468-824b-c0df323f4adf.jpg)

But there are a small error in the title page, it's duplicate.

**Comment by Heklaterriol** [comment]
@mckillo: "But there are a small error in the title page, it's duplicate."
What exactly, tell me more.

**Comment by mckillo** [comment]
If you see the Bread crumbs, the title menu is 'Single Event' and the title page is "Single Event Single Event", the h1 title is duplicate.
I have debugger the small error in site\views\tml\default.php line 47 (delete).
See commit 0d692824cd4fe7fe080c7267d4e5e3bb7c481a99  with solution (close h1 tag too).

**Comment by jojo12** [comment]
Before in resopnsive simplelist with image Ihad images width 300 and height 200,Now I installed the small chances before JEM4, And I get smallest images !Am 09.03.2023 17:28 schrieb Hekla Terriol ***@***.***>:
Please give me more details, where exactly you encountered it.

**Comment by jojo12** [comment]
You can have a look injem4test.joomla.comAgenda and MiniturnierAm 09.03.2023 18:16 schrieb Jojo Murer ***@***.***>:Before in resopnsive simplelist with image Ihad images width 300 and height 200,Now I installed the small chances before JEM4, And I get smallest images !Am 09.03.2023 17:28 schrieb Hekla Terriol ***@***.***>:
Please give me more details, where exactly you encountered it.

**Comment by jojo12** [comment]
And this with a height 400!Am 09.03.2023 18:23 schrieb Jojo Murer ***@***.***>:You can have a look injem4test.joomla.comAgenda and MiniturnierAm 09.03.2023 18:16 schrieb Jojo Murer ***@***.***>:Before in resopnsive simplelist with image Ihad images width 300 and height 200,Now I installed the small chances before JEM4, And I get smallest images !Am 09.03.2023 17:28 schrieb Hekla Terriol ***@***.***>:
Please give me more details, where exactly you encountered it.

**Comment by jojo12** [comment]
I downloaded again, now the setting width is visible, and automaticly there was width=100
Now the simplelist is ok, but the eventdetails is very small (smaller than in eventslist!

**Comment by mckillo** [comment]
@Heklaterriol Yesterday, check this issue I found small error in the title event and upload a comit about the duplicate title in event view for:
- actve menu of event view (1 event).
- set menu option - show page heating = Hide
- set JEM setting - Layout Style = Legacy
Today, I have reverted that commit (yesterday) because I have been optimizing the code and check it with others combination of these options. Forexample,if 'Show Page Heading' is hide with Default (responsive), the edit and copy icon disappear with the commit (before they change the place). It was rare.

Now, there isn't title duplicate and the edit and copy icon always are in the same place with indepence of the set options indicated.

![JEM for JL4 - Update fix title duplicate in event view when layout is legacy and default when show and hide page heading](https://user-images.githubusercontent.com/2765316/224456611-e5a016af-987e-41d6-9df6-f66e49977dfa.jpg)

In this composition, the event view is shown depending on the configuration of these options.
Upload new commit 01c36bc9cbd83e1b1a315e644b06e832fa480a5a

**Comment by mckillo** [comment]
@jojo12 I don't know if you have seen this (above).
And the "the eventdetails is very small (smaller than in eventslist!", the space for the event image depends on the space consumption of the event data part (dt-dd). That's the reason (in your web) why the image jumps to another line.

By the way, I think the minimum default value for thumb images should be 200px or 250px by default (its content looks better, if the image is vertical). I use 200-250px.
