### ISSUE TITLE
adapt the calendar date in export view

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#146]
the date format is there Y-m-d. I think, it would be better d-m-Y

**Comment by Heklaterriol** [comment]
The date format depends on the country.

Imagine the following date: 02/04/03

Which does it mean?
- 2nd of April 2003 – European style
- 4th of February 2003 – USA style
- 3rd of April 2002 – international

According to ISO 8601 the international way to represent dates is: YYYY-MM-DD

**Comment by mckillo** [comment]
Keep in mind that now this field has no treatment, since this format is saved in the database, it is also used in the filters.
If the format changes then it's necesary to do a format conversion.
It can be a enhancement in this export tool, but with  very low priority because export tool is used very little or occasionally in migratory process.
