### ISSUE TITLE
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in

### ISSUE THREAD

**Issue by jojo12** [Heklaterriol/JEM-Project#154]
Solution: site/helpers/helper.php  line 1138
```
       // $tmp = is_array($ids_in) ? $ids_in : explode(',', $ids_in);
		$tmp = is_array($ids_in) ? $ids_in : explode(',', $ids_in ?? '');
```

> https://stackoverflow.com/questions/71097927/php-8-1-explode-passing-null-to-parameter-2-string-of-type-string-is-de

**Comment by Heklaterriol** [comment]
Where do you see the deprecated message?

**Comment by jojo12** [comment]
In nearby all modules, with error 
= maximum

**Comment by mckillo** [comment]
Explode isn't the problem, it's a issue of code design.
When a module setting haven't any filter of categories or venues, the validate function return a null for the explode().

For example, In modules/mod_jem/helper.php,check the value of filter indicate in the setting module and  we have lines like these:
93:   $catids = JemHelper::getValidIds($params->get('catid'));
100: $venids = JemHelper::getValidIds($params->get('venid'));

In these cases $param->get return null, because these params (catid, venid) doesn't exist (not defined).
When this null is sending to function getValidids (call from all modules), the explode function receive the null value and we have the error of this issue.

To solve:
Add 'if'' to control null value in site\helpers\helper.php line 1138. See commit 42261cdabf236917cfd2d8dee36e09e83305ce35 
@jojo12 Check it.

**Comment by jojo12** [comment]
this works and is better than the emergency solution of stackoverflow
