### ISSUE TITLE
2.3.11: Backend>Events>table is not userfriendly to use! 

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#42]
JEM > Events: the width of the event list is not adapded to the Joomla backend, it is wider and created a horizontal scrolling.

Please adapt it to the Joomla 4 style like in the Joomla native display of Articles.
Also include the choice of the columns to be displayed (on the top right of the columns)

**Comment by Heklaterriol** [comment]
ther are too many columns, we have to discuss a solution

**Comment by jojo12** [comment]
2.3.8: I am not yet happy

**Comment by jojo12** [comment]
It is strange, I tested with different wideness:
on a wide pc -> you see all columns an there is a bottom scroll bar
on a smaller pc like surface -> you have a bottom scroll bar which ends before you get              
                                               the end of the page.
on the smallest wide like a mobile -> you find a bottom scroll bar at the bottom of the lists which let's you move til the right end of the page!
So the problem is between !!

**Comment by jojo12** [comment]
I am not happy with this page!  There are two different sliders at the bottom. With my surface e.g. I have to scroll down first to move the joomla slider and then to go back to the JEM list to get e.g. the attendees column!

**Comment by jojo12** [comment]
The solution is so simple: exchange "table-responsive" with "table" then you have only one slider( Joomla)! This is much easier to handle
Warning: But then you don't have the choice for which columns!
