### ISSUE TITLE
Import bugs

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#59]
Exported data form JML 3, PHP 7.4, JEM 2.3.5

Joomla 4.2.7, PHP 8.1.14. Fresh install of JEM 2.3.7.

**JEM Control panel > Import Data**
Import Categories: OK, but hiërachy flattend, all have root == new category "root"
Import Events, then got the error:
0 Failed to parse time string (2019-11-02 2023-02-04 09:02:00) at position 11 (2): Double date specification
(Nothing imported)

Import Venues OK
Import Cat-Events OK

**Comment by Heklaterriol** [comment]
Bug existed already in JEM 2.3.5

**Comment by jojo12** [comment]
2.3.8 this problem is for me new. In 2.3.7.a I was able to import all 4 import files. Now, there is a problem after all with events import.

**Comment by jojo12** [comment]
It seems, there was an export problem in 2.3.7.a.
I imported in two different installations files from 2.3.5 and from 2.3.8. Both workked best

**Comment by mckillo** [comment]
Testing import  categories into JEM 2.3.8 doesn't work.
![Dont import categories into jem 2 3 8](https://user-images.githubusercontent.com/2765316/221175928-efbdb254-38d7-4038-ad5b-e69d1c48b8a3.jpg)
1. Try to import categories.csv file from JEM 2.3.5. I can'tdo it, because the tables aren't empty.
2. Go to JEM categories page, but it's a clear installation, and there isn't any category by default.
3. Go to Housekeeping page to 'Delete all data (as you can see JPG).
4. Try import again, but there is one category (1 rows).
5. Go to database and there is one category 'root' in this table, it haven't been deleted.
6. If manuallly, I delete this rows in the databses, and go to importpage,I have the same results, there is a 1 rows in category. No empty, no import.

Any idea of resolve this new desgin?

I don'thave any debug. I think that it isn't necessary to have this row of root reference. If id_parent is 0 in a entry, this category is child fo root, but it depends of design. Other soluction, in the import page can do it an adjustment od the category counter -1. So, the counter of row will be 0 when there isn't any category defined.

**Comment by jojo12** [comment]
the import will work, see later in this text. BUT there is a confusion with the TABS!

Normally you will do a CSV import you have 4 exported csv-files. 
There are two TABs. Go to the other tab, which looks like that:
![tab](https://user-images.githubusercontent.com/2960236/221191138-e9166a6f-ba80-4c3c-bc08-23bfccc0a29b.png)

**Comment by jojo12** [comment]
continued:
the category "root"  you can never delete!
I don't know if the next step is logical or magical, but I do it allways the same way:
I imort always first categories then venues, then events, and last cat_events.
**before importing I set "replace" to yes**, then I import.

When you have images, you have to copy the folder images/jem and inside /small, all with content. And paste it inside your joomla.
This works: the only thing until now is the time problem: 12hours instead of 24 hours and always at least instead of 00 minutes, 
there are 02 minutes.

**Comment by jojo12** [comment]
see help:

> Eventlist-Import

Eventlist-Import: The JEM Component will self-discover which version of Eventlist (1.0.1, 1.0.2 or 1.1) is installed on your system.
CSV-Import

CSV-Import: Choose this tab, to import CSV files.

Attention

The order in which you import data in JEM is relevant for its correct working. Advised and tested is: First Venues, then Categories, then Events and then last Cat_Events.
Import Options:

Choose CSV file: Click the file button to choose a local file to import.

Replace if ID exists (otherwise create): Choose yes if you want to overwrite events with already existing IDs want. When no, every event is recreated with a new ID.

Import Events: With this button you can import Events from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

Import Categories: With this button you can import Categories from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

Import Venues: With this button you can import Venues from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

Import Cat_Events: With this button you can import Cat_Events from a CSV-formatted file. Please make sure you have prepared the file according the JEM file format (see info under 'Export Data').

**Comment by mckillo** [comment]
Boom!!   :-) 
Sorry and thank ... You have to change the color between tabs (confunses). 
I have fallen into error, I think to be in import tab, as in this comment tab editor (GitHub):
![color_tab_comment-github](https://user-images.githubusercontent.com/2765316/221218262-bcf48ffa-99e4-4379-b06c-61c65574af19.jpg)

Twice ideas:
1. A style upgrade for background colour tab:
 - Active tab: White or same colour of the background content tab.
 - Other (not active): 
 ![change_color_tab_comment-jem](https://user-images.githubusercontent.com/2765316/221219771-1d29bc62-029e-4f84-b8a0-3c3b643fdd00.jpg)

2. How eventlist is very old, it's better change de ordertabs; first JEM (Active by default) and second eventlist.

![order_color_tab_comment-jem](https://user-images.githubusercontent.com/2765316/221220444-caa513e7-1be0-4444-8d22-4062773046d7.jpg)

In the latter, in my opinion, it is clearer by background color (less confusion) and by order of use (migration from jem will be more common).

Thanks for advice about orden import test, I'm on it.

**Comment by mckillo** [comment]
@jojo12: I have error whenI Try to import events, in the first line:

![jem238_error_import_event-time_with_current_date](https://user-images.githubusercontent.com/2765316/221231391-b75abe48-0b3c-4c3e-808a-bd065b89e992.jpg)

events.csv file has (export from jem 2.3.5 active):
id;locid;dates;enddates;times;endtimes;title;alias;created_by;modified;modified_by;version;author_ip;created;introtext;meta_keywords;meta_description;recurrence_first_id;recurrence_number;recurrence_type;recurrence_counter;recurrence_limit;recurrence_limit_date;recurrence_byday;datimage;checked_out;checked_out_time;registra;unregistra;unregistra_until;maxplaces;waitinglist;hits;published;contactid;custom1;custom2;custom3;custom4;custom5;custom6;custom7;custom8;custom9;custom10;fulltext;created_by_alias;access;metadata;featured;attribs;language;categories
1;1;2015-06-17;2015-06-19;18:00:00;20:00:00;"Fiesta últimos días del clase";fiesta-ultimos-dias-del-clase;778;"0000-00-00 00:00:00";0;1;;"2015-06-11 05:02:23";;"[title], [a_name], [categories], [times]";"The event titled [title] starts on [dates]!";0;0;0;0;0;0000-00-00;;;0;"0000-00-00 00:00:00";0;0;0;0;0;2126;1;0;;;;;;;;;;;;;1;"{""robots"":"""",""author"":"""",""rights"":""""}";0;"{""event_show_author"":"""",""event_link_author"":"""",""event_show_contact"":"""",""event_link_contact"":"""",""event_show_hits"":"""",""event_show_print_icon"":"""",""event_show_email_icon"":"""",""event_show_ical_icon"":"""",""event_show_detailstitle"":"""",""event_show_locdescription"":"""",""event_show_detailsadress"":"""",""event_show_detlinkvenue"":"""",""event_show_mapserv"":"""",""event_tld"":"""",""event_lg"":"""",""event_comunsolution"":"""",""event_comunoption"":"""",""event_show_description"":""""}";;2

If I debug this error, the code reads each field, but in 4º (times) and 5º (endtimes) field compose the array with the data but add date to value for each field (see administrator\components\com_jem\controllers\import.php line 191)

![jem238_error_import_event-time_with_current_date-code_change_value_field](https://user-images.githubusercontent.com/2765316/221233419-cbc38075-6fb4-41d4-95f6-18ed188dbb07.jpg)

Into _jem_events table (DB) these fields are TIME, not DATETIME.

If it changes this line:
$field = date('Y-m-d h:m:s',$time);
For this one:
$field = date('h:m:s',$time); 
the import process for events works.

![jem238_error_import_event-time_with_current_date-solved](https://user-images.githubusercontent.com/2765316/221235841-93b83547-8378-453a-ab2a-b964f60bc79a.jpg)

**Comment by mckillo** [comment]
@jojo12 : The version 2.3.8 zip file isn't update, there are many differences files between this zip and jem-beta1 repository. This error is solved into JEM-Beta1 code. I have updated my JEM installation with repository.
It will be good have a new beta version updated 2.3.9 for JEM tester.

**Comment by Heklaterriol** [comment]
https://github.com/Heklaterriol/JEM-Project/tree/JEM-4beta1

**Comment by jojo12** [comment]
@mckillo:
I exported an event from 2.3.8 and imported it in 2.3.8 after the proposed changing in admin/controllers/import.php. I had in csv
times: 16:00:00
After import, I have: no time!

**Comment by jojo12** [comment]
After different tests, I found the solution, it must be in line 190
`					$field = date('Y-m-d H:i:s',$time);
`

**Comment by mckillo** [comment]
No, the right line (see above) is:
`$field = date('H:i:s',$time);`

**Comment by jojo12** [comment]
you wrotehttps://docs.github.com/articles/github-community-guidelines
> (in the same version don't have sense).
this is not true, because you can import other csv files!
I tested your proposal, with an event.csv file from JEM 2.3.5, then I get **NO DATE**, only the right time
When I import an event.csv file from 2.3.5 with my solution, I get the date and the right time. Sorry, but please try again!

**Comment by mckillo** [comment]
Yes, it's right, you can import events from other site with JEM and same version. 
Respect your code (controllers/import.php), if $value is '02:00' & type is 'times' or 'endtimes', 
- with you code: ` $field = date('Y-m-d H:i:s',$time); ` ant return "2023-02-27 02:00:00" (with date import has error, see in the beging).
- with my code : ` $field = date('H:i:s',$time); `  return "02:00:00", I think this is right for these fields (times, endtimes) are TIME type in the structure database.

**Comment by jojo12** [comment]
2.3.9 Problem persists!

**Comment by mckillo** [comment]
I have detected an warning during import about date = '0000-00-00', during import process is truncated, because strtotime oth this value is negative. It happess when the recurrence_limit_date field is '000-00-00', I suppose that it should be null when has this value, isn't it? This field into structure DB is null by default (no defined).

It can be solved to change this line 198 (\admin\components\com_jem\controllers\import.php function _formatcsvfield):
`if ($value !== '' && strtoupper($value) !== 'NULL') {`

for other one:
`if ($value !== '' && strtoupper($value) !== 'NULL' && $value != '0000-00-00') {`

![jem238_change_formatcsvfield-solved_error_during_import_csv-mark_yellow](https://user-images.githubusercontent.com/2765316/221842343-8560a37c-e5d6-4295-a7da-67a40da6f0d0.jpg)

I have marked in yellow this change and previous comment. Tested with 1052 events from 2.3.5 to 2.3.8. So, It works.

**Comment by mckillo** [comment]
![JEM for JL4 - import test from 2 3 5 -works_2706_events_ok](https://user-images.githubusercontent.com/2765316/221855812-12d69b4a-b125-485d-b991-2d63c2d5be65.jpg)

Second big test for import tool: 2706 events imported. It's wroking.

**Comment by mckillo** [comment]
@jojo12 : v.2.3.9 not include the change od code (see below) . \admin\components\com_jem\controllers\import.php is the same ini both version.

**Comment by jojo12** [comment]
2.3.9:
@mckillo: yes, nothing is changed here, problem persists: 
I changed what I wrote before and imported then!. all well!

**Comment by mckillo** [comment]
I'm sorry, but if I install JEM 2.3.9 and aply your code in line 190 (`$field = date('Y-m-d h:i:s',$time);`), I have the same error that v.2.3.8,

![jem239_error_import_event-time_with_current_date](https://user-images.githubusercontent.com/2765316/221925283-e3ed0adb-06d4-4bdd-a94a-22001e738844.jpg)

I don't understand because it works you, could you send me the content of you import file to test it and compare with import file of version 2.3.5

**Comment by jojo12** [comment]
I tested with mckillos commit. Works best! Thanks

**Comment by mckillo** [comment]
@Heklaterriol 2.3.10 version don't include into
pkg_jem_v2.3.10.zip\pkg_jem_v2.3.10\packages\com_jem.zip\com_jem\admin\controllers\import.php
the change of line 190 that resolve this issue:
$field = date('H:i:s',$time);
It is previus format ('Y-m-d h:m:s') and it give error when import.
Check it, thank.

**Comment by Heklaterriol** [comment]
Hi Mckillo, yes, I somehow created a chaos when merging our small fixes into the new version from the developer. I now whent back to the unmerged version from the developer and will carfully merge and test versions.
